version: '3'
services:
  api:
    build: .
    links:
      - elastic
    ports:
      - "5000:5000"
    networks:
      - pplbase
    environment:
      - ELASTIC_HOSTS=elastic localhost
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=0
    tty: true


  elastic:
    image: "elasticsearch:7.5.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - pplbase
    environment:
      - discovery.type=single-node
    volumes:
      - /c/dockerdisks:/usr/share/elasticsearch/data

networks:
  pplbase:
    driver: bridge



# WSL en docker aantekeningen, codepage errors los je op door:
# - git-bash te gebruiken (mingw)
# of:
# - in de terminal waar het mis gaat (Dos/Powershell) "chcp 850" te gebruiken

