version: '3'
services:
  api:
    build: .
    links:
      - elastic
    ports:
      - "5000:5000"
    networks:
      - pplbase
    environment:
      - ELASTIC_HOSTS=elastic localhost
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=0
    tty: true


  elastic:
    image: "elasticsearch:7.5.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - pplbase
    environment:
      - discovery.type=single-node
    volumes:
      - ${PPLBASE_STORE:-/c/dockerdisks}:/usr/share/elasticsearch/data

networks:
  pplbase:
    driver: bridge


# ELASTIC_HOSTS: space separated list of possible elasicsearch hosts, he first to answer will be used
#                the name of the host could be a docker-service-name
#
# PPLBASE_STORE: optional variable pointing to the 'local'-side of the storage definition.
#                if not set the literal /c/dockerdisks will be used as a default
#

# WSL en docker aantekeningen, codepage errors los je op door:
# - git-bash te gebruiken (mingw)
# of:
# - in de terminal waar het mis gaat (Dos/Powershell) "chcp 850" te gebruiken


